needs-more-info:
  comment: >
    :wave: @{issue-author} thanks for filing this issue. 
    
    Unfortunately, we need more information to investigate further. A project mantainer will be post on this issue soon to ask for more information.