name: "Save PR number as artifact"
description: "Save PR number as artifact"
runs:
  using: "composite"
  steps:
    - name: Save PR number
      shell: bash
      if: github.event_name == 'workflow_run'
      run: |
        let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.payload.workflow_run.id,
        });
        let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
          return artifact.name == "pr_number"
        })[0];
        let download = await github.rest.actions.downloadArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: matchArtifact.id,
            archive_format: 'zip',
        });
        let fs = require('fs');
        fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));

