name: 'Functional test run (environment)'
on:
  workflow_run:
    workflows: ['Functional test approval (environment)']
    types:
      - completed
jobs:
  functional-tests:
    name: 'Run Functional Tests (environment)'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env: 
      FUNCTIONAL_TEST_APP_ID: 412087
    steps:
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: ${{ env.FUNCTIONAL_TEST_APP_ID }}
          private_key: ${{ secrets.FUNCTIONAL_TEST_APP_PRIVATE_KEY }}
      - name: Dump event data
        env:
          DATA: ${{ toJson(github.event) }}
        run: echo "$DATA"
      # - name: Check out code
      #   uses: actions/checkout@v3
      # - uses: marocchino/sticky-pull-request-comment@v2
      #   if: success() && env.PR_NUMBER != ''
      #   continue-on-error: true
      #   with:
      #     GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token }}
      #     header: teststatus-${{ github.run_id }}
      #     number: ${{ env.PR_NUMBER }}
      #     append: true
      #     message: |
      #       :white_check_mark: Completed for PR: ${{ env.PR_NUMBER }}

