name: 'Functional test approval (environment)'
on:
  pull_request:
    branches:
      - main
      - features/*
      - release/*
jobs:
  functional-tests:
    name: 'Approve Functional Tests (environment)'
    runs-on: ubuntu-latest
    environment: functional-tests
    steps:
    - name: Save PR number
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
    - uses: actions/upload-artifact@v3
      with:
        name: pr_number
        path: pr/

