name: 'Functional test approval (environment)'
on:
  pull_request:
    branches:
      - main
      - features/*
      - release/*
jobs:
  functional-tests:
    name: 'Approve Functional Tests (environment)'
    runs-on: ubuntu-latest
    environment: functional-tests
    steps:
    - name: Save PR number
      uses: ./.github/actions/save-pr-as-artifact

